= **Lancez les tests automatisés**

Maintenant que l’environnement **staging** est déployé, il est possible de lancer des tests impossibles à lancer lors de la phase d’intégration continue. 


Nous allons lancer un **test de performance**, afin de mesurer les temps de réponse de l’application. 

Pour ce faire, vous allez utiliser **Apache Benchmark** pour simuler de la charge sur le serveur.

Ces tests peuvent être de différents types.

== **Découvrez les tests d’acceptance**

Les **tests d’acceptance** sont des tests formels exécutés pour vérifier si un système satisfait à ses exigences opérationnelles. 


Ils exigent que l’application entière soit opérationnelle et se concentrent sur la réplication des comportements des utilisateurs. 

Mais ils peuvent aussi aller plus loin, en mesurant la performance du système, et rejeter les changements si certains objectifs ne sont pas atteints.

Ces tests peuvent être **automatisés**, mais aussi **manuels**, avec une équipe de test dédiée qui regardera si le logiciel correspond au besoin.

Pour lancer des tests d’acceptance, vous pourrez utiliser **Confluence**, **FitNesse** ou **Ranorex**.

== **Découvrez les tests de performance**

Les **tests de performance** vérifient le comportement du système lorsqu’il est soumis à une charge importante. Ces tests ne sont pas fonctionnels et peuvent prendre différentes formes pour comprendre la fiabilité, la stabilité et la disponibilité de la plateforme. Par exemple, il peut s’agir d’observer les temps de réponse lors de l’exécution d’un grand nombre de requêtes, ou de voir comment le système se comporte avec une quantité importante de données.

Les tests de performance sont par nature assez coûteux à mettre en œuvre et à exécuter, mais ils peuvent vous aider à comprendre si de nouveaux changements vont dégrader votre système.

Pour faire des tests de performance, vous pourrez utiliser **JMeter**, **Apache Bench** ou **Gatling**.

### **Découvrez les smoke tests**

Les **smoke tests** sont des tests de base qui vérifient les fonctionnalités de base de l’application. Ils sont conçus pour être rapides à exécuter et leur but est de vous donner l’assurance que les **principales caractéristiques de votre système fonctionnent comme prévu**. Ils peuvent être utiles juste après une nouvelle build, pour décider si vous pouvez ou non exécuter des tests plus coûteux, ou juste après un déploiement pour s’assurer que l’application fonctionne correctement dans le nouvel environnement déployé.

Par exemple, les smoke tests peuvent s’assurer que la base de données répond et est correctement configurée, mais aussi que les différents composants sont présents et envoient des données correctes, comme des API qui devraient répondre un code HTTP 200 ou une page web qui devrait s’afficher.

Pour vous assurer du bon fonctionnement de l’application, vous pourrez utiliser **Selenium**, **SoapUI** ou **Cypress**.
