= Containers

A container is a runnable instance of an image. 


You can :
- create
- start
- stop
- move
- delete a container using the Docker API or CLI. 


You can :
- connect a container to one or more networks
- attach storage to it, 
- even create a new image based on its current state.

By default, a container is relatively well isolated from other containers and its host machine. 

You can control how isolated a container's network, storage, or other underlying subsystems are from other containers or from the host machine.

A container is defined by its image as well as any configuration options you provide to it when you create or start it. 

When a container is removed, any changes to its state that aren't stored in persistent storage disappear.

== Example docker run command

The following command runs an ubuntu container, attaches interactively to your local command-line session, and runs /bin/bash.

[source, bash]
----
docker run -i -t ubuntu /bin/bash
----

When you run this command, the following happens (assuming you are using the default registry configuration):

If you don't have the ubuntu image locally, Docker pulls it from your configured registry, as though you had run docker pull ubuntu manually.

Docker creates a new container, as though you had run a docker container create command manually.

Docker allocates a read-write filesystem to the container, as its final layer. 

This allows a running container to create or modify files and directories in its local filesystem.

Docker creates a network interface to connect the container to the default network, since you didn't specify any networking options. 

This includes assigning an IP address to the container. 

By default, containers can connect to external networks using the host machine's network connection.

Docker starts the container and executes /bin/bash. 

Because the container is running interactively and attached to your terminal (due to the -i and -t flags), you can provide input using your keyboard while Docker logs the output to your terminal.

When you run exit to terminate the /bin/bash command, the container stops but isn't removed. You can start it again or remove it.