= Ce qu'est Ansible

Ansible est un outil d'automatisation informatique écrit en Python. 

Il peut:
- configurer des systèmes,
- déployer des logiciels et orchestrer des tâches informatiques avancées, telles que des déploiements continus.

Son créateur s’appelle Michael DeHaan;

La première version de Ansible date de 2012. 

Depuis, Ansible s'enrichit constamment et une version majeure est proposée approximativement tous les deux mois.

Le nom Ansible est tiré d’un roman de science-fiction écrit par Ursula Le Guin, et qui désigne un moyen de communication plus rapide que la lumière.

Entretemps, Ansible a été racheté en 2015 par Red Hat. 

La communauté compte plus de 3 500 contributeurs.

Red Hat a été racheté par IBM en 2018. Donc, Ansible appartient désormais à IBM.



== Agentless


Ansible est un outil agentless, c’est-à-dire qu’il n’installe pas d’agent sur les nodes. 

Il travaille donc en mode push: il pousse les installations sur les nodes.

Pour cela, il n’utilise que les outils déjà présents sur la plupart des systèmes Linux : SSH et Python.

L’inverse du mode push est le mode pull. 

Par exemple, une marketplace d’applications comme le Play Store ou l’AppStore d’Apple sont des systèmes en mode pull : 

le client (le smartphone)tire les applications ou les mises à jour vers lui.

Ici, ous utiliserez votre ordinateur comme Node Manager**. Mais en pratique, il est conseillé d’avoir un serveur de référence sur lequel vous configurez un environnement d'automatisation toujours opérationnel et sécurisé, capable de se connecter aux nodes de votre infrastructure. 


De plus, si vous travaillez à plusieurs sur l’infrastructure de l’entreprise avec Ansible, c’est beaucoup plus simple de contrôler les accès et les scripts depuis un point unique.
