name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo "Testing..."

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: echo "Packaging..."

  deploy_staging_job:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - uses: actions/checkout@v2
      - name: Set PWD Variable
        run: echo "PWD=ip172-18-0-56-cqqb4ngl2o9000bln38g@direct.labs.play-with-docker.com" >> $GITHUB_ENV
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Deploy to Staging
        env:
          DOCKER_HOST: tcp://$PWD.direct.labs.play-with-docker.com:2375
        run: |
          docker compose down
          docker compose up -d
    environment:
      name: staging
      url: http://$PWD-8080.direct.labs.play-with-docker.com

  healthcheck_job:
    runs-on: ubuntu-latest
    needs: deploy_staging_job
    steps:
      - name: Healthcheck
        run: |
          if curl --fail http://$PWD-8080.direct.labs.play-with-docker.com; then
            echo "Healthcheck passed!"
          else
            echo "Healthcheck failed!" >&2
            exit 1

  canary_job:
    runs-on: ubuntu-latest
    needs: healthcheck_job
    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set DOCKER_HOST environment variable
        run: echo "DOCKER_HOST=tcp://$PLAYWD.direct.labs.play-with-docker.com:2375" >> $GITHUB_ENV

      - name: Bring down any existing containers
        run: docker-compose down

      - name: Bring up the containers
        run: docker-compose up -d
        env:
          DOCKER_HOST: ${{ env.DOCKER_HOST }}

  deploy_production_job:
    runs-on: ubuntu-latest
    needs: canary_job
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Deploy to Production
        env:
          DOCKER_HOST: tcp://$PLAYWD.direct.labs.play-with-docker.com:2375
        run: |
          docker compose down
          docker compose up -d
    if: ${{ github.event_name == 'workflow_dispatch' }} 
