name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo "Testing..."

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: echo "Packaging..."

  deploy_staging_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set PWD Variable
        run: echo "PWD=ip172-18-0-56-cqqb4ngl2o9000bln38g@direct.labs.play-with-docker.com" >> $GITHUB_ENV
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Deploy to Staging
        env:
          DOCKER_HOST: tcp://$PWD.direct.labs.play-with-docker.com:2375
          PWD: ip172-18-0-56-cqqb4ngl2o9000bln38g@direct.labs.play-with-docker.com
        run: |
          docker compose down
          docker compose up -d
    environment:
      name: staging
      url: http://$PWD-8080.direct.labs.play-with-docker.com

  healthcheck_job:
    runs-on: ubuntu-latest
    steps:
      - name: Healthcheck
        run: |
          if curl --fail http://ip172-18-0-56-cqqb4ngl2o9000bln38g@direct.labs.play-with-docker.com; then
            echo "Healthcheck passed!"
          else
            echo "Healthcheck failed!" >&2
            exit 1